name: DeFNet
channels:
  - defaults
dependencies:
  - numpy=1.17.2
  - imageio=2.6.1
  - glob2=0.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - click
  - matplotlib
  - joblib
  - Pillow=6.1
  - plotly=2.0
  - pip
  - pip:
    - gtimer
    - gym==0.14.0
    - moviepy
    # - opencv-python==4.1.1.26
    - Shapely==1.6.4.post2
    - pyquaternion==0.9.5
    - sk-video==1.1.10
    - torch==1.9.0
    # - torch==1.6.0
    - torchvision==0.10.0
    - scipy==1.5.4
    - pytorch-lightning==1.3.0
    - torchmetrics==0.7.0
    - hydra-core==1.1.1
    - matplotlib
    - omegaconf==2.1.1
    - certifi==2020.6.20
    - cycler==0.10.0
    - decorator==4.4.2
    - fonttools==4.25.0
    - joblib==0.17.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - munkres==1.1.4
    - networkx==2.5
    - numpy==1.19.2
    - olefile==0.46
    - opencv-python==4.3.0.38
    - Pillow==8.4.0
    - pip==21.2.4
    - pyparsing==3.0.3
    - python-dateutil==2.8.2
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - setuptools==58.0.4
    - sip==4.19.8
    - six==1.16.0
    - threadpoolctl==2.1.0
    # - torchvision==0.7.0
    - tornado==6.1
    - wheel==0.37.0