hydra: 
  run:
    dir: outputs/${experiment}/${now:%Y-%m-%d_%H%M%S}_picknet
  sweep:
    dir: multirun/${experiment}/${now:%Y-%m-%d_%H%M%S}_picknet
    subdir: ${hydra.job.num}

experiment: dbg

seed: 0 

base_path: /home/heruhan/gnq/paper_codes/FabricFlowNet # base directory containing train and val dirs
train_name: biman_towel_actpickplace_n500_h3_co1_am0.9_tc0.3_cam0.65_lact # train data directory name
val_name: biman_towel_actpickplace_n100_h3_co1_am0.9_tc0.3_cam0.65_lact # validation data directory name

epochs: 150 # max training epochs 
max_buf: 20000 # 7200 # max training buf
workers: 0
batch_size: 10 # batch size

check_val_every_n_epoch: 1
tboard_log_dir: tb
csv_log_dir: csv

net_cfg:
  lr: 0.0001
  input_mode: flowonly
  min_loss: True
  model_type: split
  pick: True # Whether it is pick network or place network
  im_width: 200

#flow: /home/heruhan/gnq/paper_codes/new_fabricflownet/FabricFlowNet/outputs/dbg/2022-09-11_202924_flownet/default_default/0_0/checkpoints/epoch=299-step=9599.ckpt
flow: /home/heruhan/gnq/paper_codes/FabricFlowNet/outputs/dbg/2022-11-01_125912_flownet/default_default/0_0/checkpoints/last.ckpt
augment: False # dataset spatial aug flag

debug_viz:
  remove_occlusions: False
  data_sample: False