augment: false
batch: 10
dataset_path: /media/ExtraDrive1/temp_data
debug: true
epochs: 150
eval_freq: 5000
flow: horz5_epoch=1588.ckpt
flow_align: false
gaussian_noise: false
im_width: 200
input_mode: flowonly
log_freq: 500
loss_type: sigmoid
lr: 0.0001
max_buf: 20000
min_loss: true
misalign: false
model_suffix: _nojit_h5fl_horz5
model_type: split
output_dir: /home/sujaybajracharya/cloth_folding/softagent/tshirt_exp/corlbaseline/bimanual_flow/output
pick: true
rand_depth_offset: false
run_name: biman_towel_actpickplace_n4000_h5_co1_am0.9_tc0.5_cam0.65_lact_horz5
save_freq: 5000
seed: 0
single: false
swapping: false
test_name: biman_towel_actpickplace_n400_h5_co1_am0.9_tc0.5_cam0.65_lact_horz5
